### ISSUE TITLE
Python Client support

### ISSUE THREAD

**Issue by NadavkOptimalQ** [Soluto/tweek#1004]
Are there any plans on going or in the future to add a python client?

**Comment by Yshayy** [comment]
Hi @NadavkOptimalQ,
our next version of the api will have much better OpenAPI support (defined here: https://github.com/Soluto/tweek/blob/gateway/services/gateway/swagger.yml) and we hope to use it to generate base rest clients in various languages (including Python).
Web clients will still enjoy support for more complex scenarios/integrations such as [tweek-local-cache](https://github.com/Soluto/tweek-clients/tree/master/js/tweek-local-cache) and [react-tweek](https://github.com/Soluto/tweek-clients/tree/master/js/react-tweek)

**Comment by NadavkOptimalQ** [comment]
Thanks for the quick replay @Yshayy 
Is there an estimated time schedule for the python client?
Will it have features like caching and more or will it just be an a gateway to the API?

**Comment by Yshayy** [comment]
Js clients need some of these advanced capabilities because they ran tend to run in a rich/interactive app settings (mobile/web).
In a backend ([micro]service/script/function) environment, when using node.js we just use the simple Tweek's js rest client and I believe the Python client can work in a similar way.

I hope we'll merge the gateway branch soon enough, once we have it, anyone can generate a client from it. (for example, in Python it could be based on https://github.com/swagger-api/swagger-codegen/tree/master/modules/swagger-codegen/src/main/resources/python)
 
In the future it'll be great if we'll manage to have a CI for generating these client.

Current version of Tweek also have a swagger definition: https://github.com/Soluto/docs.tweek.fm/blob/master/assets/swagger/api/0.8.3.json
But it covers only parts of the functionality and it'll be subjected to a major change after the gateway merge.

**Comment by Yshayy** [comment]
Closing, will be managed in https://github.com/Soluto/tweek-openapi-clients
