### ISSUE TITLE
Setting gradually released rule to 0% or false does not make a change

### ISSUE THREAD

**Issue by odedw** [Soluto/tweek#1346]
The only thing that made a difference was deleting the entire rule.
Here's how to recreate:
- Create a new key, created a new rule and set it open to 99%
- Query for the key with different IDs till you get `true`
- set rule to false (0%) and query again - you should still get `true`
- Only deleting the rule changes the returned value to `false`

**Comment by Yshayy** [comment]
Not sure if that's the bug, I tried to simulate it in testing environment.
1. When I clicked on "set to False" after changing to 0, the value of type change to "false" instead false in the JPad.
2. Changing it to true than false or choosing false from the select solved this issue. (it's not false)
3. When querying the api, it's important to provide the identity (for example, user=myuser) otherwise the rule is skipped.

How did you query it? (maybe the client treated "false" as truthy)

**Comment by Yshayy** [comment]
My guess is that this bug is more common than we think in production, so it's pretty critical.
I think it's worth scanning the rules repository and changing "false" and "true" values for features of type boolean.
Additionally, from the backend side, we can make the JPad engine do string conversion based on the value type to ensure correctness for legacy.
For the mean time, I created a fix for the editor #1349
