### ISSUE TITLE
Show total number of Rules per key

### ISSUE THREAD

**Issue by OrRosenblatt** [Soluto/tweek#610]
Pretty explicit. 
I will be happy to expend further on the subject, if needed.

**Comment by Yshayy** [comment]
We have rules count per partition:
http://editor.yshay.play-with-tweek.com/keys/some_key
![image](https://user-images.githubusercontent.com/1076078/30372597-0691c1de-9887-11e7-8031-0c47f1795828.png)
We can add a global rule count as well, it's should be simple to implement.

In general, large keys are really tough to control and manage by just flat rules since ordering the keys the right way can be challenging and confusing.
Due to that, we encourage large keys to use partitions and dependent keys to organize logic and when using these features the total rules count might be less relevant.
